### ISSUE TITLE
key_file - paramater missing

### ISSUE THREAD

**Issue by criyas** [tivrobo/ansible-win_git#13]
Hi

Can we use key_file  parameter using win_git? we need to attach private key along with git command

**Comment by tivrobo** [comment]
@criyas, no
but you could make it works another way
just setup ssh key based authentication for user used by ansible (ansible_user)
place private and public keys into %userprofile%\\.ssh\\, and validate from console that you able to connect to git server using ssh transport
https://www.google.com/search?q=git+ssh+key+windows
