### ISSUE TITLE
Unsure how to implement the win_git module

### ISSUE THREAD

**Issue by thatscot** [tivrobo/ansible-win_git#2]
I have added win_git,ps1 and win_git.py to a library folder which is on the same level as my playbooks folder. 

I am receiving a syntax error when I try to use the win_git module though. I think this is becuase ansible doesn't recognise the module. Do I need to reference the library folder somehow? Also will this work when both machines are windows?

**Comment by tivrobo** [comment]
@thatscot post your `ansible --version` output 
```
ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

```
content of your `config file = /etc/ansible/ansible.cfg`

**Comment by tivrobo** [comment]
@thatscot 
> Also will this work when both machines are windows?

What does you mean?

**Comment by pablodav** [comment]
I use it and don't have issues with that, my tree: 

```
.
├── ansible.cfg
├── examples
├── execute_burp.yml
├── False
├── group_vars
├── host_vars
├── inventory
├── library
├── roles
├── site.yml
├── sql_servers.yml
├── task_execute_backup_restore_sql_servers.yml
├── tasks
├── test_playbook.yml
├── windows-install-requirements.yml
├── windows-patches.yml
├── windows-updates-all.yml
└── win_git_test.yml
```

**Comment by arshadzackeriya** [comment]
hi @pablodav 

its a really good module but i am having a weird issue as below.

this is my playbook
`- name: connect to windows server
  hosts: windows

  gather_facts: false
  tasks:
    - name: execute the remote file
      win_git:
         name: "git@bitbucket.org:arshadz/satest.git"
         dest: "C:\\inetpub\\wwwroot\\sa.local"
         replace_dest: no
         accept_hostkey: yes
         update: pull origin master
         branch: test`

this is the error.

`fatal: [192.168.122.53]: FAILED! => {
    "changed": false, 
    "msg": "Failed to checkout to master", 
    "win_git": {
        "accept_hostkey": true, 
        "branch": "master", 
        "branch_status": "", 
        "dest": "C:\\inetpub\\wwwroot\\sa.local", 
        "git_opts": "--no-pager pull origin master", 
        "method": "pull", 
        "name": "git@bitbucket.org:arshadz/satest.git", 
        "replace_dest": false, 
        "update": "pull origin master"
    }
}
	to retry, use: --limit @/etc/ansible/windows/group_vars/wingit.retry
`

when i changed the branch it hangs and nothing happen. could you please help me

**Comment by tivrobo** [comment]
@arshadzackeriya 
> "msg": "Failed to checkout to master"

This is error message from git executable.
Do you have success when trying to checkout using git command by your hands?
This is what Google says: https://stackoverflow.com/questions/12596767/why-i-cannot-checkout-another-git-branch
