### ISSUE TITLE
You cannot call a method on a null-valued expression

### ISSUE THREAD

**Issue by michael-hay** [tivrobo/ansible-win_git#4]
I am running 

`[user@server dir]$ ansible --version
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/rserve_user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
`

I have your module in my playbook library and am trying to create a very simple playbook using win_git

`---
# This playbook uses the win_ping module to test connectivity to Windows hosts
- name: Clone 
  hosts: clients

  tasks:
  - name: Git Clone Repo
    win_git:
      name: "ssh://git@stash:port/foo/repoName.git"
      dest: "C:\\temp"
      replace_dest: yes
      accept_hostkey: yes
      update: yes
      branch: master
`

I get an error back from powershell complaining about a null value

`PLAY [Clone] *********************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************
ok: [server]

TASK [Git Clone Repo] ****************************************************************
fatal: [server]: FAILED! => {"changed": false, "msg": "Error cloning ssh://git@stash:port/foo/repoName.git to C:\\temp! Msg: You cannot call a method on a null-valued expression. - ", "win_git": {"accept_hostkey": true, "branch": "master", "dest": "C:\\temp", "git_opts": "--no-pager pull origin master", "method": "pull", "name": "ssh://git@stash:port/foo/repoName.git", "replace_dest": true, "update": true, "valid_url": "ssh://git@stash:port/foo/repoName.git is valid url"}}
	to retry, use: --limit @/home/user/repo/clone.retry

PLAY RECAP ***********************************************************************************************************
server                 : ok=1    changed=0    unreachable=0    failed=1   
`

I tried using different options but still no dice.

If I comment out the checkout function from the clone and update I no longer get an error but I still get no repo cloned.  Any ideas?

**Comment by pablodav** [comment]
could be probably due to some change in ansible 2.5, it works fine for me in 2.4 but I'm just starting to test 2.5.
Once I have some time I will test this module in 2.5 and will back here.

**Comment by michael-hay** [comment]
I figured out how to debug this.  I will open a PR.

**Comment by tivrobo** [comment]
#5 merged
thanks guys!
