### ISSUE TITLE
Support git clone recursive for submodules

### ISSUE THREAD

**Issue by kakawait** [tivrobo/ansible-win_git#9]
Currently if your git repo has submodules, those submodules are not fetched because close is not recursive

Do you think is possible to add `recursive` option like on official _no windows_ module https://docs.ansible.com/ansible/latest/modules/git_module.html ?

**Comment by tivrobo** [comment]
@kakawait, I think its possible, I will review it

**Comment by tivrobo** [comment]
please test: 2b252ecfb41eb0b89edd261d74da8fead8bd5920

**Comment by kakawait** [comment]
@tivrobo I tested branch `feature/add-recursive-option` and it works like a charm.

**Comment by tivrobo** [comment]
@kakawait, cool :) I will merge it with master

**Comment by tivrobo** [comment]
done! in #10
